(() => {
'use strict';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let editingId=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
async function guard(){const {data:{user}}=await sb.auth.getUser();if(!user){adminGuard.innerHTML='<h2>Admin sign-in required</h2><p>Go to the store and sign in with your admin email.</p><button class="primary" onclick="location.href=\'index.html\'">Go to ShopNest</button>';return false}const {data:p}=await sb.from('profiles').select('role,full_name').eq('id',user.id).maybeSingle();if(p?.role!=='admin'){adminGuard.innerHTML='<h2>Access denied</h2><p>This account is not an admin.</p><button onclick="location.href=\'index.html\'">Back to Store</button>';return false}adminGuard.classList.add('hidden');adminApp.classList.remove('hidden');return true}
async function loadAdminProducts(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});productTable.innerHTML=error?'<p>'+esc(error.message)+'</p>':`<div class="table-wrap"><table><thead><tr><th>Photo</th><th>Product</th><th>Category</th><th>Supplier</th><th>Selling</th><th>Stock</th><th>Active</th><th>Actions</th></tr></thead><tbody>${(data||[]).map(p=>`<tr><td><img class="thumb" src="${esc(p.image_url||'')}" alt=""></td><td><b>${esc(p.name)}</b><br><small>${esc((p.description||'').slice(0,80))}</small></td><td>${esc(p.category)}</td><td>${money(p.supplier_price)}</td><td>${money(p.selling_price)}</td><td>${p.stock}</td><td>${p.is_active?'Yes':'No'}</td><td><button onclick="editProduct('${p.id}')">Edit</button><button onclick="toggleProduct('${p.id}',${!p.is_active})">${p.is_active?'Hide':'Show'}</button><button onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
window.loadAdminProducts=loadAdminProducts;
window.editProduct=async id=>{const {data:p}=await sb.from('products').select('*').eq('id',id).single();if(!p)return;editingId=id;formTitle.textContent='Edit Product';productId.value=id;pName.value=p.name||'';pBrand.value=p.brand||'';pShortDescription.value=p.short_description||'';pCategory.value=p.category||'Other';pDescription.value=p.description||'';pHighlights.value=Array.isArray(p.highlights)?p.highlights.join('\n'):'';pSpecifications.value=Object.entries(p.specifications||{}).map(([k,v])=>`${k}: ${v}`).join('\n');pSupplier.value=p.supplier_price||'';pSelling.value=p.selling_price||'';pStock.value=p.stock||0;imageStatus.textContent=p.image_url?'Existing photo kept unless a new one is selected.':'No photo';imagePreview.innerHTML=p.image_url?`<img class="preview" src="${esc(p.image_url)}">`:'';scrollTo({top:0,behavior:'smooth'})};
window.resetProductForm=()=>{editingId=null;formTitle.textContent='Add Product';productId.value='';pName.value='';pBrand.value='';pShortDescription.value='';pCategory.value='Electronics';pDescription.value='';pHighlights.value='';pSpecifications.value='';pSupplier.value='';pSelling.value='';pStock.value='';pImage.value='';imageStatus.textContent='Upload up to 5 MB.';imagePreview.innerHTML=''};
async function uploadImage(file){if(!file)return null;if(file.size>5242880)throw new Error('Image must be 5 MB or smaller.');if(!file.type.startsWith('image/'))throw new Error('Only image files are allowed.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('product-images').upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}
window.saveProduct=async()=>{try{const name=pName.value.trim(),brand=pBrand.value.trim(),short_description=pShortDescription.value.trim(),description=pDescription.value.trim(),supplier=Number(pSupplier.value),selling=Number(pSelling.value),stock=Number(pStock.value),category=pCategory.value;if(!name||!description||supplier<0||selling<0||stock<0)return alert('Fill all required product fields correctly.');const highlights=pHighlights.value.split('\n').map(x=>x.trim()).filter(Boolean);const specifications={};pSpecifications.value.split('\n').forEach(line=>{const i=line.indexOf(':');if(i>0){const k=line.slice(0,i).trim();const v=line.slice(i+1).trim();if(k&&v)specifications[k]=v;}});let imageUrl=null;const file=pImage.files[0];if(file)imageUrl=await uploadImage(file);const payload={name,brand,short_description,description,highlights,specifications,category,supplier_price:supplier,selling_price:selling,stock,is_active:true};if(imageUrl)payload.image_url=imageUrl;let res;if(editingId)res=await sb.from('products').update(payload).eq('id',editingId);else res=await sb.from('products').insert(payload);if(res.error)throw res.error;alert(editingId?'Product updated.':'Product added.');resetProductForm();await loadAdminProducts()}catch(e){alert(e.message)}};
window.toggleProduct=async(id,active)=>{const {error}=await sb.from('products').update({is_active:active}).eq('id',id);if(error)alert(error.message);else loadAdminProducts()};window.deleteProduct=async id=>{if(!confirm('Delete this product?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)alert(error.message);else loadAdminProducts()};
async function loadAdminOrders(){const {data,error}=await sb.from('orders').select('*').order('created_at',{ascending:false});orderTable.innerHTML=error?'<p>'+esc(error.message)+'</p>':`<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Address</th><th>Total</th><th>Status</th><th>Update</th></tr></thead><tbody>${(data||[]).map(o=>`<tr><td>${esc(o.id.slice(0,8))}<br><small>${new Date(o.created_at).toLocaleString()}</small></td><td>${esc(o.customer_name)}<br>${esc(o.phone)}</td><td>${esc([o.address_line1,o.city,o.state,o.pincode].filter(Boolean).join(', '))}</td><td>${money(o.total_amount)}</td><td><b>${esc(o.status)}</b></td><td><select onchange="setOrderStatus('${o.id}',this.value)"><option value="processing" ${o.status==='processing'?'selected':''}>Processing</option><option value="shipped" ${o.status==='shipped'?'selected':''}>Shipped</option><option value="delivered" ${o.status==='delivered'?'selected':''}>Delivered</option><option value="done" ${o.status==='done'?'selected':''}>Done</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelled</option></select></td></tr>`).join('')}</tbody></table></div>`}
window.loadAdminOrders=loadAdminOrders;window.setOrderStatus=async(id,status)=>{const {error}=await sb.rpc('admin_set_order_status',{p_order_id:id,p_status:status});if(error)alert(error.message);else loadAdminOrders()};
async function loadAdminReturns(){const {data,error}=await sb.from('returns').select('*').order('requested_at',{ascending:false});returnTable.innerHTML=error?'<p>'+esc(error.message)+'</p>':`<div class="table-wrap"><table><thead><tr><th>Return</th><th>Order</th><th>User</th><th>Reason</th><th>Status</th></tr></thead><tbody>${(data||[]).map(r=>`<tr><td>${esc(r.id.slice(0,8))}</td><td>${esc(r.order_id.slice(0,8))}</td><td>${esc(r.user_id.slice(0,8))}</td><td>${esc(r.reason)}</td><td>${esc(r.status)}</td></tr>`).join('')}</tbody></table></div>`}
window.loadAdminReturns=loadAdminReturns;window.adminLogout=async()=>{await sb.auth.signOut();location.href='index.html'};
pImage.addEventListener('change',()=>{const f=pImage.files[0];imagePreview.innerHTML=f?`<img class="preview" src="${URL.createObjectURL(f)}">`:''});
document.addEventListener('DOMContentLoaded',async()=>{if(await guard()){await loadAdminProducts();await loadAdminOrders();await loadAdminReturns()}});
})();
