(() => {
'use strict';
const sb = window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let PRODUCTS=[],category='All',selected=null,detailQty=1,cart=[],buyNowMode=false;
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const getUser=async()=>{const {data}=await sb.auth.getUser();return data.user};
function saveCart(){try{localStorage.setItem('sn_cart',JSON.stringify(cart))}catch(e){} updateCartCount()}
function loadCart(){try{cart=JSON.parse(localStorage.getItem('sn_cart')||'[]')}catch(e){cart=[]}updateCartCount()}
function updateCartCount(){const e=document.getElementById('cartCount');if(e)e.textContent=cart.reduce((s,x)=>s+x.quantity,0)}
async function loadProducts(){const {data,error}=await sb.from('products').select('*').eq('is_active',true).gt('stock',0).order('created_at',{ascending:false});if(error){document.getElementById('productGrid').innerHTML='<p>'+esc(error.message)+'</p>';return}PRODUCTS=data||[];renderProducts()}
function renderProducts(){const q=(document.getElementById('search')?.value||'').toLowerCase();let a=PRODUCTS.filter(p=>(category==='All'||p.category===category)&&(!q||[p.name,p.description,p.category].some(x=>String(x||'').toLowerCase().includes(q))));const sort=document.getElementById('sort')?.value;if(sort==='low')a.sort((x,y)=>x.selling_price-y.selling_price);if(sort==='high')a.sort((x,y)=>y.selling_price-x.selling_price);const g=document.getElementById('productGrid');g.innerHTML=a.length?a.map(p=>`<article class="card"><div class="card-click" onclick="openProductDetails('${p.id}')"><img src="${esc(p.image_url||'')}" alt="${esc(p.name)}"><span class="badge">${esc(p.category||'Other')}</span><h3>${esc(p.name)}</h3><div class="price">${money(p.selling_price)}</div><div class="muted">${Number(p.stock)} in stock</div></div><div class="row"><button onclick="addToCart('${p.id}')">Add</button><button class="primary" onclick="quickBuy('${p.id}')">Buy Now</button></div></article>`).join(''):'<p>No products found.</p>'}
window.setCategory=b=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.cat||'All';renderProducts()};
window.openProductDetails=id=>{selected=PRODUCTS.find(p=>p.id===id);if(!selected)return;detailQty=1;document.getElementById('detailImage').src=selected.image_url||'';document.getElementById('detailName').textContent=selected.name;document.getElementById('detailBadge').textContent=selected.category||'PRODUCT';document.getElementById('detailPrice').textContent=money(selected.selling_price);document.getElementById('detailStock').textContent=`In stock: ${selected.stock}`;document.getElementById('detailDescription').textContent=selected.description||'No description available.';document.getElementById('detailCategory').textContent=selected.category||'Other';document.getElementById('detailProductId').textContent=selected.id.slice(0,8);document.getElementById('detailQuantity').textContent='1';document.getElementById('productDetailsModal').classList.remove('hidden')};
window.closeProductDetails=()=>document.getElementById('productDetailsModal').classList.add('hidden');window.increaseDetailQty=()=>{if(selected)detailQty=Math.min(detailQty+1,Number(selected.stock));document.getElementById('detailQuantity').textContent=detailQty};window.decreaseDetailQty=()=>{detailQty=Math.max(1,detailQty-1);document.getElementById('detailQuantity').textContent=detailQty};
window.addToCart=(id,qty=1)=>{const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const e=cart.find(x=>x.productId===id);if(e)e.quantity=Math.min(e.quantity+qty,p.stock);else cart.push({productId:p.id,name:p.name,quantity:qty,unitPrice:Number(p.selling_price),supplierPrice:Number(p.supplier_price),image_url:p.image_url||''});saveCart();alert('Added to cart.')};window.addDetailToCart=()=>{if(selected){addToCart(selected.id,detailQty);closeProductDetails()}};window.quickBuy=id=>{selected=PRODUCTS.find(p=>p.id===id);if(!selected)return;cart=[];addToCart(id,1);buyNowMode=true;openCheckout()};window.buyNow=()=>{if(!selected)return;cart=[];addToCart(selected.id,detailQty);closeProductDetails();buyNowMode=true;openCheckout()};
window.openCart=()=>{renderCart();document.getElementById('cartModal').classList.remove('hidden')};window.closeCart=()=>document.getElementById('cartModal').classList.add('hidden');function total(){return cart.reduce((s,x)=>s+x.unitPrice*x.quantity,0)}function renderCart(){const b=document.getElementById('cartItems');b.innerHTML=cart.length?cart.map((x,i)=>`<div class="order-card"><b>${esc(x.name)}</b><div>${money(x.unitPrice)} × ${x.quantity}</div><div class="row"><button onclick="changeQty(${i},-1)">−</button><button onclick="changeQty(${i},1)">+</button><button onclick="removeCart(${i})">Remove</button></div></div>`).join(''):'<p>Your cart is empty.</p>';document.getElementById('cartTotal').textContent=money(total())};window.changeQty=(i,d)=>{if(!cart[i])return;const p=PRODUCTS.find(x=>x.id===cart[i].productId);cart[i].quantity=Math.max(1,Math.min(cart[i].quantity+d,Number(p?.stock||99)));saveCart();renderCart()};window.removeCart=i=>{cart.splice(i,1);saveCart();renderCart()};
window.openCheckout=async()=>{if(!cart.length)return alert('Cart is empty.');const u=await getUser();if(!u){closeCart();openAccount();return alert('Login first.')}const {data:p}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();if(p){checkoutName.value=p.full_name||'';checkoutPhone.value=p.phone||''}closeCart();checkoutModal.classList.remove('hidden')};window.closeCheckout=()=>checkoutModal.classList.add('hidden');
window.placeOrder=async()=>{const u=await getUser();if(!u)return alert('Login first.');const name=checkoutName.value.trim(),phone=checkoutPhone.value.trim(),address=checkoutAddress.value.trim(),city=checkoutCity.value.trim(),state=checkoutState.value.trim(),pincode=checkoutPincode.value.trim();if(!name||!phone||!address||!city||!state||!pincode||!checkoutConsent.checked)return alert('Complete all details.');if(!cart.length)return alert('Cart is empty.');const items=cart.map(x=>({product_id:x.productId,quantity:Number(x.quantity)}));const {data:orderId,error}=await sb.rpc('create_order',{p_customer_name:name,p_phone:phone,p_address_line1:address,p_address_line2:'',p_city:city,p_state:state,p_pincode:pincode,p_items:items});if(error)return alert(error.message);cart=[];saveCart();buyNowMode=false;closeCheckout();successModal.classList.remove('hidden');loadProducts()};window.closeSuccess=()=>successModal.classList.add('hidden');
function accountHtml(){return `<h3>Sign in</h3><p class="muted">Use your ShopNest email and password. No OTP or sign-in link is required.</p><input id="loginEmail" class="otp-input" type="email" autocomplete="email" placeholder="Email"><input id="loginPassword" class="otp-input" type="password" autocomplete="current-password" placeholder="Password"><button class="primary wide" onclick="loginWithPassword()">Login</button><hr><h3>Create Account</h3><input id="signupName" class="otp-input" autocomplete="name" placeholder="Full name"><input id="signupPhone" class="otp-input" autocomplete="tel" placeholder="Phone"><input id="signupEmail" class="otp-input" type="email" autocomplete="email" placeholder="Email"><input id="signupPassword" class="otp-input" type="password" autocomplete="new-password" placeholder="Password (min 8 characters)"><input id="signupPassword2" class="otp-input" type="password" autocomplete="new-password" placeholder="Confirm password"><button class="wide" onclick="createPasswordAccount()">Create Account</button>`}
window.openAccount=async()=>{const b=accountBody;b.innerHTML='<p>Loading...</p>';accountModal.classList.remove('hidden');const u=await getUser();if(!u){b.innerHTML=accountHtml();return}const {data:p}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();b.innerHTML=`<h3>Welcome, ${esc(p?.full_name||'Customer')}</h3><p>${esc(u.email||'')}</p><div class="row"><button onclick="showMyOrders()">My Orders</button><button onclick="showMyProfile()">Profile</button><button onclick="logout()">Logout</button></div><div id="accountContent"></div>`;showMyOrders()};
window.loginWithPassword=async()=>{const email=loginEmail.value.trim(),password=loginPassword.value;if(!email||!password)return alert('Enter email and password.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert(error.message);accountBtn.textContent='Account';closeAccount();await roleRedirect(data.user)};
window.createPasswordAccount=async()=>{const email=signupEmail.value.trim(),name=signupName.value.trim(),phone=signupPhone.value.trim(),password=signupPassword.value,password2=signupPassword2.value;if(!email||!name||!phone||!password||!password2)return alert('Fill all fields.');if(password.length<8)return alert('Password must be at least 8 characters.');if(password!==password2)return alert('Passwords do not match.');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,phone}}});if(error)return alert(error.message);if(data.session){alert('Account created successfully.');accountBtn.textContent='Account';closeAccount();await roleRedirect(data.user)}else alert('Account created. If email confirmation is enabled in Supabase, confirm the email once before logging in.');};
async function roleRedirect(u){if(!u)return;const {data:p}=await sb.from('profiles').select('role').eq('id',u.id).maybeSingle();if(p?.role==='admin'&&!location.pathname.endsWith('/admin.html'))location.href='admin.html'}window.showMyOrders=async()=>{const b=document.getElementById('accountContent'),u=await getUser();if(!b||!u)return;const {data,error}=await sb.from('orders').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(error)return b.innerHTML='<p>'+esc(error.message)+'</p>';b.innerHTML='<h4>My Orders</h4>'+(data?.length?data.map(o=>`<div class="order-card"><b>${esc(o.id.slice(0,8))}</b><br>Status: ${esc(o.status)}<br>Total: ${money(o.total_amount)}<br><small>${new Date(o.created_at).toLocaleString()}</small>${o.status==='processing'?`<br><button onclick="cancelOrder('${o.id}')">Cancel</button>`:''}${o.status==='delivered'?`<br><button onclick="returnOrder('${o.id}')">Request Return</button>`:''}</div>`).join(''):'<p>No orders yet.</p>')};window.cancelOrder=async id=>{const r=prompt('Cancellation reason:');if(r===null)return;const {error}=await sb.rpc('cancel_order',{p_order_id:id,p_reason:r||'Customer cancelled'});if(error)alert(error.message);else{alert('Order cancelled.');showMyOrders()}};window.returnOrder=async id=>{const r=prompt('Return reason:');if(r===null)return;const {error}=await sb.rpc('request_return',{p_order_id:id,p_reason:r||'Customer return request'});if(error)alert(error.message);else{alert('Return request submitted.');showMyOrders()}};window.showMyProfile=async()=>{const u=await getUser(),{data:p}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();accountContent.innerHTML=`<h4>Profile</h4><p><b>Name:</b> ${esc(p?.full_name||'-')}</p><p><b>Phone:</b> ${esc(p?.phone||'-')}</p><p><b>Email:</b> ${esc(u.email||'-')}</p><hr><h4>Set / Change Password</h4><input id="newPassword" class="otp-input" type="password" placeholder="New password (min 8 characters)"><button onclick="setPassword()">Save Password</button>`};window.setPassword=async()=>{const pw=newPassword.value;if(!pw||pw.length<8)return alert('Password must be at least 8 characters.');const {error}=await sb.auth.updateUser({password:pw});if(error)alert(error.message);else alert('Password saved. You can now login with email + password.')};window.logout=async()=>{await sb.auth.signOut();closeAccount();accountBtn.textContent='Login'};window.closeAccount=()=>accountModal.classList.add('hidden');
sb.auth.onAuthStateChange((_e,s)=>{if(s?.user){setTimeout(()=>roleRedirect(s.user),0);accountBtn.textContent='Account'}});
document.addEventListener('DOMContentLoaded',()=>{loadCart();search.addEventListener('input',renderProducts);sort.addEventListener('change',renderProducts);document.querySelectorAll('.cat').forEach(b=>b.addEventListener('click',()=>setCategory(b)));loadProducts();sb.auth.getSession().then(({data:{session}})=>{if(session){accountBtn.textContent='Account';roleRedirect(session.user)}})});
})();
